/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY, 
    name varchar(100),
    date_of_birth DATE,
    escape_attempts INT,
    neutered  BOOLEAN,
    weight_kg DECIMAL
);

ALTER TABLE animals
    ADD species varchar(100);

CREATE TABLE owners (
    id serial not null primary key,
    full_name varchar(100),
    age INT
);    

CREATE TABLE species (
    id serial not null primary key,
    name varchar(100)
);    

ALTER TABLE animals
ADD species_id INT;


ALTER TABLE animals
ADD CONSTRAINT constraint_fk
FOREIGN KEY (species_id)
REFERENCES species(id);

ALTER TABLE animals
ADD owner_id INT;

ALTER TABLE animals
ADD CONSTRAINT constraint_fk2
FOREIGN KEY (owner_id)
REFERENCES owners(id);