/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY, 
    name varchar(100),
    date_of_birth DATE,
    escape_attempts INT,
    neutered  BOOLEAN,
    weight_kg DECIMAL
);

ALTER TABLE animals
    ADD species varchar(100);

CREATE TABLE owners (
    id serial not null primary key,
    full_name varchar(100),
    age INT
);    

CREATE TABLE species (
    id serial not null primary key,
    name varchar(100)
);    

ALTER TABLE animals
ADD species_id INT;


ALTER TABLE animals
ADD CONSTRAINT constraint_fk
FOREIGN KEY (species_id)
REFERENCES species(id);

ALTER TABLE animals
ADD owner_id INT;

ALTER TABLE animals
ADD CONSTRAINT constraint_fk2
FOREIGN KEY (owner_id)
REFERENCES owners(id);

CREATE TABLE vets (
    id serial not null primary key, 
    name varchar(100),
    age INT,
    date_of_graduation DATE
);

CREATE TABLE specializations(
    vets_id INT,
    species_id INT,
    FOREIGN KEY (vets_id) REFERENCES vets(id),
    FOREIGN KEY (species_id) REFERENCES species(id)
); 

ALTER TABLE animals
ADD CONSTRAINT uq_animals_id UNIQUE (id);

CREATE TABLE visits(
    vets_id INT,
    animals_id INT,
    date_of_visit DATE,
    FOREIGN KEY (vets_id) REFERENCES vets(id),
    FOREIGN KEY (animals_id) REFERENCES animals(id)
); 

-- Add an email column to your owners table
ALTER TABLE owners ADD COLUMN email VARCHAR(120);

/* Creating indexes to improve the execution time of the queries */
CREATE INDEX visits_animals_id_idx ON visits (animals_id);
CREATE INDEX visits_vets_id_idx ON visits (vets_id);
CREATE INDEX owners_email_idx ON owners (email);